name: Job exporting RUN sections of github jobs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export-run-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo snap install yq

      - name: Parsing job yaml files and export run commands
        env:
          echo "ACTIONS_RUNNER_DEBUG: true
        run: |
          source ./scripts/toolbox.sh
          
          workflows_dir=".github/workflows"
          
          find "$workflows_dir" -type f -print0 | while IFS= read -r -d '' file; do
            f=$(basename "$file")
            f_without_extension="${f%.*}"
            note "Job file processed: $workflows_dir/$f"
            ./scripts/export-run-job.sh $workflows_dir/$f > job-$f_without_extension.txt
            
            # Move the generated job files to the desired location within the repository
            mv job-$f_without_extension.txt generated/
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated new play demo files"
          commit_user_name: "cmoulliard"
          commit_user_email: "cmoulliard@redhat.com"