name: Job exporting RUN sections of github jobs

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export-run-commands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Parsing job yaml files and export run commands
        env:
          echo "ACTIONS_RUNNER_DEBUG: true
        run: |
          #source ./scripts/toolbox.sh
          #
          #workflows_dir=".github/workflows"
          #
          #find "$workflows_dir" -type f -print0 | while IFS= read -r -d '' file; do
          #  filename=$(basename "$file")
          #  note "Job file name: $workflows_dir/$filename"
          #  ./scripts/export-run-job.sh $workflows_dir/$filename 2> errors.log
          #done
          #
          ## Move the generated job files to the desired location within the repository
          #mv job*.txt generated/
          
          #!/usr/bin/env bash
          #source ./scripts/toolbox.sh
          
          sudo snap install yq
          
          set -x
          
          parse_yaml() {
            yaml_file="$1"
            
            for job in $(yq eval -o=j $yaml_file | jq -cr '.jobs[]'); do
              echo $job
            done
          }
        
          main() {
            if [ $# -eq 0 ]; then
              echo "Usage: $0 <github_workflow.yml>"
              exit 1
            fi
        
            parse_yaml "$1"
          }
          
          main ./.github/workflows/job-2.yml

      #- name: Log errors
      #  if: failure()
      #  run: |
      #    cat errors.log

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated new jobs files"
          commit_user_name: "cmoulliard"
          commit_user_email: "cmoulliard@redhat.com"