name: Python Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up run environment
        uses: actions/checkout@v3

      - name: Install Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python test
        run: pytest > pytest.log 2>&1
        continue-on-error: true

      - name: Upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-log
          path: pytest.log

      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "Job failed!"
